package com.flagcamp.dispatchanddelivery.service;

import com.flagcamp.dispatchanddelivery.entity.UserEntity;
import com.flagcamp.dispatchanddelivery.repository.AuthorityRepository;
import com.flagcamp.dispatchanddelivery.repository.UserRepository;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserService {
    private final UserRepository userRepository;
    private final AuthorityRepository authorityRepository;
    private final PasswordEncoder passwordEncoder;

    public UserService(
            UserRepository userRepository,
            AuthorityRepository authorityRepository,
            PasswordEncoder passwordEncoder
    ) {
        this.userRepository = userRepository;
        this.authorityRepository = authorityRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Transactional
    public void signUp(String email, String password) {
        email = email.toLowerCase();

        // Check if the user already exists in the system
        UserEntity existingUser = userRepository.findByEmail(email);
        if (existingUser != null) {
            throw new IllegalStateException("User already exists");
        }

        // Create new user entity (let database generate UUID)
        UserEntity newUser = new UserEntity(
                null,  // ID will be auto-generated by database
                email,
                passwordEncoder.encode(password),
                true   // enabled by default
        );
        
        // Save user to database
        UserEntity savedUser = userRepository.save(newUser);
        
        // Create authority (role) for the user
        authorityRepository.insertAuthority(savedUser.email(), "ROLE_USER");
    }

    public UserEntity getUserByEmail(String email) {
        return userRepository.findByEmail(email);
    }
}
